import type { Locale } from "./locales";

const en = {
  target: {
    heading: "Translation caption languages",
    selected: "selected",
    sourceAria: "Source language",
    sourceAlways: "Source · always available",
    groupAria: "Select translation caption languages",
    minOne: "At least one translation language is required.",
    sourceArrow: "source",
    latencyHint: "Adding target languages can increase local translation calls and segment finalization latency.",
  },
  display: {
    title: "Caption display settings",
    surfaces: "Projector · OBS · audience screen",
    lines: "lines",
    font: "Font",
    systemFont: "System default",
    size: "Caption size",
    maxLines: "Maximum lines",
    align: "Alignment",
    center: "Center",
    left: "Left",
    hold: "Caption hold time",
    continuous: "Until next caption",
    seconds: "sec",
    holdHelp: "0 seconds keeps the current caption until the next one arrives.",
    showSource: "Show source below translation",
    showSourceHelp: "When a translated caption is selected, show the source as a secondary line.",
    reset: "Restore defaults",
  },
  share: {
    eyebrow: "Audience access",
    wifiHint: "Audience members can scan the QR code on the same Wi-Fi network.",
    readableAddress: "Readable address",
    network: "Access network",
    noLan: "No usable LAN address was found. Check Wi-Fi or Ethernet connectivity.",
    mdnsFallback: "mDNS is unavailable, so the IP address will be used for sharing.",
    copyAudience: "Copy audience link",
    openProjector: "Open projector",
    copyObs: "Copy OBS URL",
    checkingLan: "Checking LAN address",
    networkError: "Could not determine a LAN address.",
    qrError: "Could not generate the QR code.",
    qrAlt: "Audience join QR code",
  },
  onboarding: {
    aria: "Initial setup",
    title: "LangTextFlow initial setup",
    close: "Close initial setup",
    progress: "Initial setup progress",
    steps: ["Start", "System", "Microphone", "Languages", "Finish"],
    introTitle: "Check what is required before starting realtime captions.",
    introBody: "We will check speech recognition, translation, microphone access, and default languages in order, then suggest a safe configuration based on what is already installed.",
    introNote: "Operating-system packages and drivers are never changed without your approval.",
    systemTitle: "System configuration",
    systemChecking: "Checking ASR and translation environment…",
    systemHttp: "System check HTTP",
    systemFailed: "System check failed.",
    ready: "Ready to run with the current configuration",
    attention: "Some items are not ready in the current configuration.",
    recommended: "Recommended configuration",
    applyRecommended: "Apply recommended configuration",
    fallbackPrep: "Prepare ASR fallback",
    fallbackModel: "speech recognition model can be downloaded in advance.",
    fallbackDetail: "Prepare the local cache now so downloading does not start during a session.",
    translationPrep: "Prepare translation model",
    translationPrepTitle: "The selected translation model can be prepared now.",
    translationPrepDetail: "Download the model into the running Ollama instance and automatically recheck when it completes.",
    micTitle: "Microphone / audio input",
    micBody: "Check whether the browser can use a real input device. The test stream is closed immediately after permission is confirmed.",
    micUnchecked: "Microphone check required",
    micChecking: "Checking",
    micReady: "Microphone ready",
    micFailed: "Microphone check failed",
    micInitialDetail: "Not checked yet.",
    micCheckingDetail: "Checking microphone permission and input devices…",
    micUnsupported: "This browser does not support the audio input API.",
    micNoDevice: "No available audio input device.",
    micFoundPrefix: "Audio inputs detected",
    micGenericFailed: "Could not check the microphone.",
    micAction: "Check microphone",
    basicsTitle: "Default usage settings",
    sourceLanguage: "Source language",
    useCase: "Use case",
    speechRecognition: "Speech recognition",
    translation: "Translation",
    noTranslation: "No translation",
    translationModel: "Translation model",
    exactModelId: "Enter the exact model id returned by /v1/models.",
    finishedTitle: "Initial setup is complete.",
    finishedBody: "Enter a session title, presenter, and important terms, then start captions. You can recheck system status anytime from the operator preflight panel.",
    language: "Languages",
    later: "Later",
    previous: "Previous",
    next: "Next",
    begin: "Get started",
  },
} as const;

type Widen<T> = T extends string
  ? string
  : T extends readonly string[]
    ? readonly string[]
    : { [K in keyof T]: Widen<T[K]> };

type PanelCopy = Widen<typeof en>;

const ko: PanelCopy = {
  target: {
    heading: "번역 자막 언어",
    selected: "개 선택",
    sourceAria: "원문 언어",
    sourceAlways: "원문 · 항상 제공",
    groupAria: "번역 자막 언어 선택",
    minOne: "번역 언어는 최소 1개가 필요합니다.",
    sourceArrow: "원문",
    latencyHint: "대상 언어가 늘면 로컬 번역 호출 수와 segment 확정 지연도 증가할 수 있습니다.",
  },
  display: {
    title: "자막 표시 설정",
    surfaces: "프로젝터 · OBS · 청중 화면",
    lines: "줄",
    font: "글꼴",
    systemFont: "시스템 기본",
    size: "자막 크기",
    maxLines: "최대 행수",
    align: "정렬",
    center: "가운데",
    left: "왼쪽",
    hold: "자막 유지시간",
    continuous: "계속",
    seconds: "초",
    holdHelp: "0초는 다음 자막이 올 때까지 현재 자막을 유지합니다.",
    showSource: "번역 아래 원문 함께 표시",
    showSourceHelp: "번역 자막을 선택했을 때 원문을 보조 줄로 표시합니다.",
    reset: "기본값으로 복원",
  },
  share: {
    eyebrow: "청중 접속",
    wifiHint: "청중은 같은 Wi-Fi에서 QR을 스캔하면 됩니다.",
    readableAddress: "사람이 읽기 쉬운 주소",
    network: "접속 네트워크",
    noLan: "사용 가능한 LAN 주소를 찾지 못했습니다. Wi-Fi/Ethernet 연결을 확인하세요.",
    mdnsFallback: "mDNS를 사용할 수 없어 IP 주소로 공유합니다.",
    copyAudience: "청중 링크 복사",
    openProjector: "프로젝터 열기",
    copyObs: "OBS URL 복사",
    checkingLan: "LAN 주소 확인 중",
    networkError: "LAN 주소를 확인하지 못했습니다.",
    qrError: "QR 코드를 생성하지 못했습니다.",
    qrAlt: "청중 접속 QR 코드",
  },
  onboarding: {
    aria: "초기 설정",
    title: "LangTextFlow 초기 설정",
    close: "초기 설정 닫기",
    progress: "초기 설정 진행률",
    steps: ["시작", "시스템", "마이크", "언어", "완료"],
    introTitle: "실시간 자막을 시작하기 전에 필요한 항목을 확인합니다.",
    introBody: "음성 인식, 번역, 마이크와 기본 언어를 순서대로 점검합니다. 설치되어 있는 구성요소를 기준으로 안전한 기본 설정도 제안합니다.",
    introNote: "운영체제 패키지나 드라이버는 사용자 동의 없이 변경하지 않습니다.",
    systemTitle: "시스템 구성",
    systemChecking: "ASR/번역 환경을 확인하는 중입니다…",
    systemHttp: "시스템 점검 HTTP",
    systemFailed: "시스템 점검에 실패했습니다.",
    ready: "현재 설정으로 실행 가능",
    attention: "현재 설정에 준비되지 않은 항목이 있습니다.",
    recommended: "권장 구성",
    applyRecommended: "권장 구성 적용",
    fallbackPrep: "ASR fallback 준비",
    fallbackModel: "음성 인식 모델을 미리 받을 수 있습니다.",
    fallbackDetail: "세션 도중 다운로드가 시작되지 않도록 지금 로컬 cache를 준비합니다.",
    translationPrep: "번역 모델 준비",
    translationPrepTitle: "선택한 번역 모델을 준비할 수 있습니다.",
    translationPrepDetail: "실행 중인 Ollama에 모델을 내려받고 완료 후 자동으로 다시 점검합니다.",
    micTitle: "마이크 / 오디오 입력",
    micBody: "브라우저가 실제 입력 장치를 사용할 수 있는지 확인합니다. 권한 확인 후 테스트 스트림은 즉시 종료합니다.",
    micUnchecked: "마이크 확인 필요",
    micChecking: "확인 중",
    micReady: "마이크 준비 완료",
    micFailed: "마이크 확인 실패",
    micInitialDetail: "아직 확인하지 않았습니다.",
    micCheckingDetail: "마이크 권한과 입력 장치를 확인하는 중입니다…",
    micUnsupported: "이 브라우저는 오디오 입력 API를 지원하지 않습니다.",
    micNoDevice: "사용 가능한 오디오 입력 장치가 없습니다.",
    micFoundPrefix: "확인된 오디오 입력",
    micGenericFailed: "마이크를 확인하지 못했습니다.",
    micAction: "마이크 점검",
    basicsTitle: "기본 사용 설정",
    sourceLanguage: "입력 언어",
    useCase: "사용 목적",
    speechRecognition: "음성 인식",
    translation: "번역",
    noTranslation: "번역 사용 안 함",
    translationModel: "번역 모델",
    exactModelId: "/v1/models가 반환하는 정확한 model id를 입력하세요.",
    finishedTitle: "초기 설정이 완료되었습니다.",
    finishedBody: "세션 이름과 발표자, 필요 용어를 입력한 뒤 자막을 시작할 수 있습니다. 시스템 상태는 운영자 화면의 사전점검 패널에서 언제든 다시 확인할 수 있습니다.",
    language: "언어",
    later: "나중에",
    previous: "이전",
    next: "다음",
    begin: "시작하기",
  },
};

const ja: PanelCopy = {
  target: {
    heading: "翻訳字幕の言語",
    selected: "件選択",
    sourceAria: "原文言語",
    sourceAlways: "原文 · 常に表示可能",
    groupAria: "翻訳字幕言語を選択",
    minOne: "翻訳言語は少なくとも1つ必要です。",
    sourceArrow: "原文",
    latencyHint: "対象言語を増やすと、ローカル翻訳の呼び出し回数とセグメント確定の遅延が増える場合があります。",
  },
  display: {
    title: "字幕表示設定",
    surfaces: "プロジェクター · OBS · 視聴者画面",
    lines: "行",
    font: "フォント",
    systemFont: "システム既定",
    size: "字幕サイズ",
    maxLines: "最大行数",
    align: "配置",
    center: "中央",
    left: "左",
    hold: "字幕保持時間",
    continuous: "次の字幕まで",
    seconds: "秒",
    holdHelp: "0秒にすると、次の字幕が来るまで現在の字幕を表示します。",
    showSource: "翻訳の下に原文を表示",
    showSourceHelp: "翻訳字幕を選択したときに、原文を補助行として表示します。",
    reset: "既定値に戻す",
  },
  share: {
    eyebrow: "視聴者アクセス",
    wifiHint: "視聴者は同じWi-Fi上でQRコードを読み取るだけで参加できます。",
    readableAddress: "読みやすいアドレス",
    network: "接続ネットワーク",
    noLan: "利用可能なLANアドレスが見つかりません。Wi-FiまたはEthernet接続を確認してください。",
    mdnsFallback: "mDNSを利用できないため、IPアドレスで共有します。",
    copyAudience: "視聴者リンクをコピー",
    openProjector: "プロジェクターを開く",
    copyObs: "OBS URLをコピー",
    checkingLan: "LANアドレスを確認中",
    networkError: "LANアドレスを確認できませんでした。",
    qrError: "QRコードを生成できませんでした。",
    qrAlt: "視聴者参加QRコード",
  },
  onboarding: {
    aria: "初期設定",
    title: "LangTextFlow 初期設定",
    close: "初期設定を閉じる",
    progress: "初期設定の進行状況",
    steps: ["開始", "システム", "マイク", "言語", "完了"],
    introTitle: "リアルタイム字幕を始める前に必要な項目を確認します。",
    introBody: "音声認識、翻訳、マイク、既定言語を順番に確認し、インストール済みの構成に基づいて安全な設定を提案します。",
    introNote: "OSパッケージやドライバーは、ユーザーの同意なく変更しません。",
    systemTitle: "システム構成",
    systemChecking: "ASR/翻訳環境を確認しています…",
    systemHttp: "システムチェック HTTP",
    systemFailed: "システムチェックに失敗しました。",
    ready: "現在の設定で実行できます",
    attention: "現在の設定には準備が必要な項目があります。",
    recommended: "推奨構成",
    applyRecommended: "推奨構成を適用",
    fallbackPrep: "ASRフォールバックを準備",
    fallbackModel: "音声認識モデルを事前に取得できます。",
    fallbackDetail: "セッション中にダウンロードが始まらないよう、今ローカルキャッシュを準備します。",
    translationPrep: "翻訳モデルを準備",
    translationPrepTitle: "選択した翻訳モデルを準備できます。",
    translationPrepDetail: "実行中のOllamaにモデルをダウンロードし、完了後に自動で再確認します。",
    micTitle: "マイク / 音声入力",
    micBody: "ブラウザが実際の入力デバイスを利用できるか確認します。権限確認後、テストストリームはすぐ終了します。",
    micUnchecked: "マイク確認が必要です",
    micChecking: "確認中",
    micReady: "マイク準備完了",
    micFailed: "マイク確認失敗",
    micInitialDetail: "まだ確認していません。",
    micCheckingDetail: "マイク権限と入力デバイスを確認しています…",
    micUnsupported: "このブラウザは音声入力APIをサポートしていません。",
    micNoDevice: "利用可能な音声入力デバイスがありません。",
    micFoundPrefix: "検出した音声入力",
    micGenericFailed: "マイクを確認できませんでした。",
    micAction: "マイクを確認",
    basicsTitle: "基本使用設定",
    sourceLanguage: "入力言語",
    useCase: "用途",
    speechRecognition: "音声認識",
    translation: "翻訳",
    noTranslation: "翻訳しない",
    translationModel: "翻訳モデル",
    exactModelId: "/v1/models が返す正確な model id を入力してください。",
    finishedTitle: "初期設定が完了しました。",
    finishedBody: "セッション名、発表者、必要な用語を入力して字幕を開始できます。システム状態はオペレーター画面の事前チェックパネルからいつでも確認できます。",
    language: "言語",
    later: "後で",
    previous: "戻る",
    next: "次へ",
    begin: "開始する",
  },
};

export const PANEL_COPY: Record<Locale, PanelCopy> = { en, ko, ja };
